language: python
python:
  - "3.7"

before_install:
  - pip install poetry

install:
  - poetry install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - poetry run pytest --cov=mashov

after_script:
  - poetry run ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT